### ISSUE TITLE
Chris | Personal Success

### ISSUE THREAD

**Issue by chrispycheng** [dartmouth-cs98/rekall-mobile#16]
*what does success for this class mean to you?*

* I learn how to integrate Unity applications with backend functionality
* I learn how to build backend APIs to support front-end functionality - from building the API with C to hosting the database on MongoDB to hosting the backend on Heroku + integrating with authentication
* I learn how to use React and React Native and successfully build a mobile app component to support the VR side of our project

## Challenges
* Learning React and React Native from scratch and on the go will be pretty tough
* Coordinating with Ashley Francisco on React development remotely - making sure to use version control correctly
* Like Ashley Song said, "The team has a diverse range of skills and everyone is at a different level of experience with app development." I have less practical experience with building apps than the others so I'm trying my best to keep up and pull my weight!

**Comment by timofei7** [comment]
API with C? :-) 

love how much learning is happening on this project!
