### ISSUE TITLE
Ashley F Personal Success

### ISSUE THREAD

**Issue by ashleychari1234** [dartmouth-cs98/rekall-mobile#21]
# Ashley Francisco | Personal Goals
*what does success for this class mean to you?*
* Personal success means I get to contribute to our main project in a valuable way, such as helping with design and coming up with innovative ideas
* I think I would also feel successful in this class if I am able to contribute heavily to the mobile application portion of our project
* I think my final success would be getting the social media aspect of our mobile app to work fully and connect it to the VR application

## Challenges
*what are some challenges you foresee?*

* I see some challenges with communication. The remote aspect of this class makes it hard for people to know exactly how far everyone is and/or when things are going to get done. I also think that everyone has different levels of experience with web, mobile, and application development, so sometimes one teammate might fully restructure code without discussing it with another teammate.
* Last term I was not able to contribute very much because I was placed on the backend for our project. I was very unfamiliar with the backend structure and how to approach the set up for the VR application. Alongside the lack of experience with backend development, I was working with a very hectic and busy schedule and dealing with personal issues, which made it difficult for me to finish things at the pace that the group needed. So, when I would get to a task, it was usually already completed by another teammate. I don't think this will be as big of a challenge this term, but I can see it becoming a challenge when time becomes more constrained and course loads pick up.
* I think another challenge has to deal with the application itself. One challenge will be to connect all of the mobile application information to the VR application and making sure everything flows smoothly.

**Comment by timofei7** [comment]
looking like the project is evolving in interesting ways!  hope things are going well, but let me know if you want to chat about any specifics.
